version: "3.9"

services:
  backend:
    image: khawlabusaleh/assessment-backend:latest
    container_name: assessment-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    restart: unless-stopped

  frontend:
    image: khawlabusaleh/assessment-frontend:latest
    container_name: assessment-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped


