name: Build & Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # BACKEND IMAGE
      - name: Build backend image
        run: |
          docker build -t khawla/assessment-backend:latest ./backend

      - name: Push backend image
        run: |
          docker push khawla/assessment-backend:latest

      # FRONTEND IMAGE
      - name: Build frontend image
        run: |
          docker build -t khawla/assessment-frontend:latest ./frontend

      - name: Push frontend image
        run: |
          docker push khawla/assessment-frontend:latest


